import {
  type CodeGenerator,
  type Constant,
  type Doc,
  type Field,
  type Method,
  type RecordKey,
  type RecordLocation,
  type ResolvedType,
  type Value,
  unquoteAndUnescape,
} from "skir-internal";
import { z } from "zod";
import {
  DEFAULT_NAMESPACE,
  formatIntWithSeparators,
  getModuleName,
  getOutputPath,
  groupDigits,
  toFieldName,
} from "./naming.js";
import { TypeSpeller } from "./type_speller.js";

const Config = z.strictObject({
  namespace: z.string().optional(),
});

type Config = z.infer<typeof Config>;

class ElixirGenerator implements CodeGenerator<Config> {
  readonly id = "skir-elixir-gen";
  readonly configType = Config;

  generateCode(input: CodeGenerator.Input<Config>): CodeGenerator.Output {
    const namespace = input.config.namespace ?? DEFAULT_NAMESPACE;
    const speller = new TypeSpeller(input.recordMap, namespace);
    const files: CodeGenerator.OutputFile[] = [];

    const gen = new ElixirFileGenerator(speller, namespace, input.recordMap);

    for (const module of input.modules) {
      const records = module.records;
      const constants = module.constants as readonly Constant<false>[];
      const methods = module.methods as readonly Method<false>[];

      if (
        records.length === 0 &&
        constants.length === 0 &&
        methods.length === 0
      ) {
        continue;
      }

      files.push({
        path: getOutputPath(module.path),
        code: gen.generate(records, constants, methods, module.path),
      });
    }

    return { files };
  }
}

class ElixirFileGenerator {
  constructor(
    private readonly speller: TypeSpeller,
    private readonly namespace: string,
    private readonly recordMap: ReadonlyMap<RecordKey, RecordLocation>,
  ) {}

  generate(
    records: readonly RecordLocation[],
    constants: readonly Constant<false>[],
    methods: readonly Method<false>[],
    modulePath: string,
  ): string {
    const parts: string[] = [];

    for (const loc of records) {
      parts.push(
        loc.record.recordType === "struct"
          ? this.emitStruct(loc)
          : this.emitEnum(loc),
      );
    }

    // if (constants.length) parts.push(this.emitConstants(constants, modulePath));

    // if (methods.length) parts.push(this.emitMethods(methods, modulePath));

    if (constants.length || methods.length) {
      parts.push(this.emitMethodsAndConstants(methods, constants, modulePath));
    }

    const banner =
      "# Generated by `skir-elixir-gen`. Do not edit this file manually.\n";
    return banner + parts.join("\n").trimEnd() + "\n";
  }

  private emitStruct(loc: RecordLocation): string {
    const pathPrefix = this.derivePathPrefix(loc.modulePath);
    let customizedNamespace = pathPrefix 
      ? `${this.namespace}.${pathPrefix}` 
      : this.namespace;

    const moduleName = getModuleName(loc, customizedNamespace);
    const { record } = loc;
    
    const lines: string[] = [
      `defmodule ${moduleName} do`,
      this.moduleDocFalse(),
      // "",
    ];

    const useOpts: string[] = [];
    if (record.recordNumber != null) {
      useOpts.push(`id: ${formatIntWithSeparators(record.recordNumber)}`);
    }
    useOpts.push(`module_path: ${JSON.stringify(loc.modulePath)}`);

    const qName = this.qualifiedName(loc);
    useOpts.push(`qualified_name: ${JSON.stringify(qName)}`);

    const structDoc = this.docText(record.doc);
    if (structDoc) {
      useOpts.push(this.formatUseDocOpt(structDoc));
    }
    lines.push(this.emitUseMacro("Skir.Struct", useOpts));

    const fieldsByNumber = new Map<number, Field<false>>();
    for (const f of record.fields) {
      fieldsByNumber.set(f.number, f);
    }

    const removed = new Set(record.removedNumbers);
    const maxSlot = record.numSlotsInclRemovedNumbers;
    const body: string[] = [];

    for (let slot = 0; slot < maxSlot; slot++) {
      if (removed.has(slot)) {
        body.push(`  removed ${slot}`);
        continue;
      }
      const field = fieldsByNumber.get(slot);
      if (!field || !field.type) continue;

      const name = toFieldName(field.name.text);
      const typeExpr = this.speller.spell(field.type);
      const fdoc = this.docText(field.doc);

      if (fdoc.includes("\n")) {
        body.push(this.renderCommentLines(fdoc, "  "));
      }

      const docOpt = this.formatInlineDocOpt(fdoc);
      body.push(`  field :${name}, ${typeExpr}, ${slot}${docOpt}`);
    }

    if (body.length > 0) {
      lines.push("", ...body);
    }

    lines.push("end\n");
    return lines.join("\n");
  }

  private emitEnum(loc: RecordLocation): string {
    const pathPrefix = this.derivePathPrefix(loc.modulePath);
    let customizedNamespace = pathPrefix 
      ? `${this.namespace}.${pathPrefix}` 
      : this.namespace;

    const moduleName = getModuleName(loc, customizedNamespace);
    const { record } = loc;
    
    const lines: string[] = [
      `defmodule ${moduleName} do`,
      this.moduleDocFalse(),
      // "",
    ];

    const useOpts: string[] = [];
    if (record.recordNumber != null) {
      useOpts.push(`id: ${formatIntWithSeparators(record.recordNumber)}`);
    }
    useOpts.push(`module_path: ${JSON.stringify(loc.modulePath)}`);

    const qName = this.qualifiedName(loc);
    useOpts.push(`qualified_name: ${JSON.stringify(qName)}`);

    const enumDoc = this.docText(record.doc);
    if (enumDoc) {
      useOpts.push(this.formatUseDocOpt(enumDoc));
    }
    lines.push(this.emitUseMacro("Skir.Enum", useOpts));

    const variants = [...record.fields].sort((a, b) => a.number - b.number);
    const body: string[] = [];

    for (const variant of variants) {
      const name = toFieldName(variant.name.text);
      const vdoc = this.docText(variant.doc);

      if (vdoc.includes("\n")) {
        body.push(this.renderCommentLines(vdoc, "  "));
      }

      const docOpt = this.formatInlineDocOpt(vdoc);

      if (variant.type) {
        const wraps = this.speller.spell(variant.type);
        body.push(
          `  variant :${name}, ${variant.number}, wraps: ${wraps}${docOpt}`,
        );
      } else {
        body.push(`  variant :${name}, ${variant.number}${docOpt}`);
      }
    }

    // Emit removed variant numbers.
    for (const n of record.removedNumbers) {
      body.push(`  removed ${n}`);
    }

    if (body.length > 0) {
      lines.push("", ...body);
    }

    lines.push("end\n");
    return lines.join("\n");
  }

  private emitMethodsAndConstants(methods: readonly Method<false>[], constants: readonly Constant<false>[], modulePath: string): string {
    const pathPrefix = this.derivePathPrefix(modulePath);
    let customizedNamespace = pathPrefix 
      ? `${this.namespace}.${pathPrefix}` 
      : this.namespace;

    // module head
    const lines: string[] = [
      `defmodule ${customizedNamespace} do`,
      this.moduleDocFalse(),
    ];

    // constants
    if (constants.length) {
      lines.push(...["  use Skir.Constants", ""]);

      for (const constant of constants) {
        if (!constant.type) continue;
        const name = toFieldName(constant.name.text);
        const typeExpr = this.speller.spell(constant.type);
        const valueExpr = this.valueExpr(constant.value, constant.type);

        const rawDoc = this.docText(constant.doc);
        if (rawDoc) {
          lines.push(this.renderCommentLines(rawDoc, "  "));
        }
        lines.push(`  defconst :${name}, ${typeExpr}, ${valueExpr}`);
      }
    }

    // methods
    if (methods.length) {
      if (constants.length) lines.push("");
      
      lines.push(...["  use Skir.Methods", ""]);

      for (const method of methods) {
        if (!method.requestType || !method.responseType) continue;
        const name = toFieldName(method.name.text);
        const req = this.speller.spell(method.requestType);
        const resp = this.speller.spell(method.responseType);
        const mdoc = this.docText(method.doc);

        if (mdoc.includes("\n")) {
          lines.push(this.renderCommentLines(mdoc, "  "));
        }

        const docPart = this.formatInlineDocOpt(mdoc);
        lines.push(
          `  method :${name}, ${formatIntWithSeparators(method.number)}, request: ${req}, response: ${resp}${docPart}`,
        );
      }
    }

    // module end
    lines.push("end\n");
    return lines.join("\n");
  }

  private emitConstants(constants: readonly Constant<false>[], modulePath: string): string {
    const pathPrefix = this.derivePathPrefix(modulePath);
    let customizedNamespace = pathPrefix 
      ? `${this.namespace}.${pathPrefix}` 
      : this.namespace;

    const lines: string[] = [
      `defmodule ${customizedNamespace}.Constants do`,
      this.moduleDocFalse(),
      "  use Skir.Constants",
      "",
    ];

    for (const constant of constants) {
      if (!constant.type) continue;
      const name = toFieldName(constant.name.text);
      const typeExpr = this.speller.spell(constant.type);
      const valueExpr = this.valueExpr(constant.value, constant.type);

      const rawDoc = this.docText(constant.doc);
      if (rawDoc) {
        lines.push(this.renderCommentLines(rawDoc, "  "));
      }
      lines.push(`  defconst :${name}, ${typeExpr}, ${valueExpr}`);
    }

    lines.push("end\n");
    return lines.join("\n");
  }

  private emitMethods(methods: readonly Method<false>[], modulePath: string): string {
    const pathPrefix = this.derivePathPrefix(modulePath);
    let customizedNamespace = pathPrefix 
      ? `${this.namespace}.${pathPrefix}` 
      : this.namespace;

    const lines: string[] = [
      `defmodule ${customizedNamespace}.Methods do`,
      this.moduleDocFalse(),
      "  use Skir.Methods",
      "",
    ];

    for (const method of methods) {
      if (!method.requestType || !method.responseType) continue;
      const name = toFieldName(method.name.text);
      const req = this.speller.spell(method.requestType);
      const resp = this.speller.spell(method.responseType);
      const mdoc = this.docText(method.doc);

      if (mdoc.includes("\n")) {
        lines.push(this.renderCommentLines(mdoc, "  "));
      }

      const docPart = this.formatInlineDocOpt(mdoc);
      lines.push(
        `  method :${name}, ${formatIntWithSeparators(method.number)}, request: ${req}, response: ${resp}${docPart}`,
      );
    }

    lines.push("end\n");
    return lines.join("\n");
  }

  private valueExpr(value: Value, type: ResolvedType): string {
    switch (type.kind) {
      case "optional": {
        if (value.kind === "literal" && value.token.text === "null") {
          return "nil";
        }
        return this.valueExpr(value, type.other);
      }
      case "array": {
        if (value.kind !== "array") return "[]";
        const items = value.items.map((i) => this.valueExpr(i, type.item));
        return `[${items.join(", ")}]`;
      }
      case "primitive": {
        if (value.kind !== "literal") return "nil";
        return this.primitiveExpr(value.token.text, type.primitive);
      }
      case "record": {
        const loc = this.recordMap.get(type.key);
        if (!loc) return "nil";
        return loc.record.recordType === "struct"
          ? this.structExpr(value, loc)
          : this.enumExpr(value, loc);
      }
    }
  }

  private primitiveExpr(tokenText: string, primitive: string): string {
    switch (primitive) {
      case "bool":
        return tokenText === "true" ? "true" : "false";

      case "int32":
        return formatIntWithSeparators(Number(tokenText));

      case "int64":
      case "hash64": {
        if (tokenText.length > 15 || !/^-?\d+$/.test(tokenText)) {
          return groupDigits(tokenText);
        }
        return formatIntWithSeparators(Number(tokenText));
      }

      case "float32":
      case "float64": {
        if (tokenText.startsWith('"') || tokenText.startsWith("'")) {
          const special = unquoteAndUnescape(tokenText);
          switch (special) {
            case "Infinity":
              return ":infinity";
            case "-Infinity":
              return ":neg_infinity";
            case "NaN":
            default:
              return ":nan";
          }
        }
        if (
          !tokenText.includes(".") &&
          !tokenText.toLowerCase().includes("e")
        ) {
          return `${tokenText}.0`;
        }
        return tokenText;
      }

      case "string":
        return JSON.stringify(unquoteAndUnescape(tokenText));

      case "bytes": {
        const raw = unquoteAndUnescape(tokenText);
        const hex = raw.startsWith("hex:") ? raw.slice(4) : raw;
        if (hex.length === 0) return `""`;

        const pairs = hex.match(/.{1,2}/g);
        if (!pairs) return `""`;
        const bytes = pairs.map((p) => `0x${p.toUpperCase()}`);
        return `<<${bytes.join(", ")}>>`;
      }

      case "timestamp":
        return this.isoToUTCSigil(unquoteAndUnescape(tokenText));

      default:
        return tokenText;
    }
  }

  private isoToUTCSigil(iso: string): string {
    const d = new Date(iso);
    const body = (() => {
        if (Number.isNaN(d.getTime())) return iso;
        else return d
        .toISOString()
        .replace("T", " ")
        .replace(/\.000Z$/, "Z");
    })();
    
    return `~U[${body}]`;
  }

  private structExpr(value: Value, loc: RecordLocation): string {
    const pathPrefix = this.derivePathPrefix(loc.modulePath);
    const targetNamespace = pathPrefix 
      ? `${this.namespace}.${pathPrefix}` 
      : this.namespace;

    const moduleName = getModuleName(loc, targetNamespace);

    if (value.kind !== "object") {
      return `%${moduleName}{}`;
    }

    const parts: string[] = [];
    for (const field of loc.record.fields) {
      if (!field.type) continue;
      const entry = value.entries[field.name.text];
      if (!entry) continue;
      const name = toFieldName(field.name.text);
      parts.push(`${name}: ${this.valueExpr(entry.value, field.type)}`);
    }

    return value.partial
      ? `${moduleName}.partial(%{${parts.join(", ")}})`
      : `%${moduleName}{${parts.join(", ")}}`;
  }

private enumExpr(value: Value, loc: RecordLocation): string {
    // Trace the destination path from the targeted record location
    const pathPrefix = this.derivePathPrefix(loc.modulePath);
    let targetNamespace = pathPrefix 
      ? `${this.namespace}.${pathPrefix}` 
      : this.namespace;

    // Extract the clean ancestors string to build the accurate module identifier
    const recordParts = loc.recordAncestors.map((r) => r.name.text);
    if (!recordParts.includes(loc.record.name.text)) {
      recordParts.push(loc.record.name.text);
    }
    const moduleName = `${targetNamespace}.${recordParts.join(".")}`;

    // Evaluate value variants safely against the accurate moduleName identifier
    if (value.kind === "literal") {
      const vt = value.type;
      return vt && vt.kind === "enum"
        ? `:${toFieldName(vt.variant.name.text)}`
        : ":unknown";
    }

    if (value.kind === "object") {
      const kindEntry = value.entries["kind"];
      const valueEntry = value.entries["value"];
      if (kindEntry?.value.kind !== "literal") return ":unknown";

      const variantName = unquoteAndUnescape(kindEntry.value.token.text);
      const variantDecl = loc.record.fields.find(
        (f) => f.name.text === variantName,
      );

      if (!variantDecl?.type || !valueEntry) return ":unknown";

      return `{:${toFieldName(variantName)}, ${this.valueExpr(valueEntry.value, variantDecl.type)}}`;
    }

    return ":unknown";
  }

  private docText(doc: Doc): string {
    return doc.pieces
      .map((p) =>
        p.kind === "text"
          ? p.text
          : "`" + p.referenceRange.text.slice(1, -1) + "`",
      )
      .join("")
      .trim();
  }

  private emitUseMacro(macroName: string, opts: string[]): string {
    if (opts.length === 0) return `  use ${macroName}`;
    if (opts.length === 1) return `  use ${macroName}, ${opts[0]}`;

    const indentedOpts = opts.map((opt, index) => {
      const isLast = index === opts.length - 1;
      return `    ${opt}${isLast ? "" : ","}`;
    });

    return `  use ${macroName},\n${indentedOpts.join("\n")}`;
  }

  private formatUseDocOpt(rawText: string): string {
    if (!rawText.includes("\n")) {
      return `doc: ~S"${rawText}"`;
    }
    const indentedBody = rawText
      .split("\n")
      .map((line) => (line ? `    ${line}` : ""))
      .join("\n");

    return `doc: ~S"""\n${indentedBody}\n    """`;
  }

  private formatInlineDocOpt(rawText: string): string {
    if (!rawText || rawText.includes("\n")) return "";
    return `, doc: ~S"${rawText}"`;
  }

  private renderCommentLines(rawText: string, indent: string): string {
    return rawText
      .split("\n")
      .map((line) => (line ? `${indent}# ${line}` : `${indent}#`))
      .join("\n");
  }

  private moduleDocFalse(): string {
    return "  @moduledoc false";
  }

  private qualifiedName(loc: RecordLocation): string {
    const parts = loc.recordAncestors.map((r) => r.name.text);
    if (!parts.includes(loc.record.name.text)) {
      parts.push(loc.record.name.text);
    }
    return parts.join(".");
  }

  private derivePathPrefix(modulePath: string): string {
    let cleanPath = modulePath;
    if (cleanPath.endsWith(".skir")) {
      cleanPath = cleanPath.slice(0, -5);
    } else if (cleanPath.endsWith(".ex")) {
      cleanPath = cleanPath.slice(0, -3);
    }

    cleanPath = cleanPath.replace(/^[\./]+/, "");
    const segments = cleanPath.split("/").filter(Boolean);

    return segments
      .map((segment) => {
        let sanitized = segment.replace(/[^a-zA-Z0-9_\-]/g, "");

        if (/^\d/.test(sanitized)) {
          sanitized = "Mod" + sanitized;
        }

        const words = sanitized.split(/[_\-]/).filter(Boolean);
        return words
          .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
          .join("");
      })
      .join(".");
  }
}

export const GENERATOR = new ElixirGenerator();